### ISSUE TITLE
ApplicationPayload Deserialize fails when type is RefreshTokenPayload

### ISSUE THREAD

**Issue by Bandgren** [JetBrains/space-dotnet-sdk#12]
Hi again @maartenba !

i dont know if this is a follow up problem to the issue you helped solve on friday https://github.com/JetBrains/space-dotnet-sdk/issues/11

But when 

Trying to do this:
`var pay = JsonSerializer.Deserialize<ApplicationPayload>(req.Body, JsonSerializerOptions);`

results in:

```
System.Text.Json.JsonException: The JSON value could not be converted to JetBrains.Space.Common.PermissionScope. Path: $.scope | LineNumber: 0 | BytePositionInLine: 279.
 ---> System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'String'.
   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at System.Text.Json.JsonDocument.TryGetNamedPropertyValue(Int32 index, ReadOnlySpan`1 propertyName, JsonElement& value)
   at JetBrains.Space.Common.Json.Serialization.JsonElementExtensions.GetStringValue(JsonElement jsonElement, String propertyName)
   at JetBrains.Space.Common.Json.Serialization.UrlParameterConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at JetBrains.Space.Common.Json.Serialization.Polymorphism.ClassNameDtoTypeConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ContinueDeserialize[TValue](ReadBufferState& bufferState, JsonReaderState& jsonReaderState, ReadStack& readStack, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.ReadFromStream[TValue](Stream utf8Json, JsonTypeInfo jsonTypeInfo)
   at Intropy.BFF.Space.TeamsCall.Run(HttpRequestData req, FunctionContext executionContext) in /Users/bandgren/dev/space/platform/Intropy/components/Intropy.BFF.Space/src/TeamsCall.cs:line 44
```

I did a semi try of doing what you do here: https://github.com/JetBrains/space-dotnet-sdk/blob/f56ae1a7629931ab08058c43b618be52d26a7979/src/JetBrains.Space.AspNetCore/Experimental/WebHooks/SpaceWebHookRequestHandler.cs#L202

e.g 
```
        using var inputStreamReader = new StreamReader(req.Body);
        var inputJsonString = await inputStreamReader.ReadToEndAsync();
            
        // Deserialize model
        if (JsonSerializer.Deserialize(inputJsonString, typeof(ApplicationPayload), JsonSerializerOptions) is ApplicationPayload payload)
        {
            PropagatePropertyAccessPathHelper.SetAccessPathForValue(string.Empty, false, payload);
            var p = payload;
        }
```

but that results in the same exception throw, so im maybe leaning to that we might have missed something on Friday on that fix? #11 https://github.com/JetBrains/space-dotnet-sdk/commit/f56ae1a7629931ab08058c43b618be52d26a7979

Thanks in advance! 🌷

**Comment by maartenba** [comment]
The deserialize method of the custom converter hasn't been implemented, as it wasn't expected to be used 😅  I know what I'll be doing on Monday, will get that sorted.

**Comment by maartenba** [comment]
NuGet packages with version `2.0.0-beta.v2023.3.0-DEV.171709.9162` should fix the issue. Note this change only supports deserializing `PermissionScope`, other `IUrlParameter` types are not supported (as they are only meant to be used in requests to Space).

**Comment by Bandgren** [comment]
Works like a charm, thank you once again @maartenba!
<img width="641" alt="image" src="https://github.com/JetBrains/space-dotnet-sdk/assets/53816703/ab6fb53b-25dc-4000-ba95-55d18a5394ad">
