### ISSUE TITLE
CodeReviewParticipantWebhookEvent can be deserialized

### ISSUE THREAD

**Issue by Dabbel** [JetBrains/space-dotnet-sdk#13]
Hello,

the `CodeReviewParticipantWebhookEvent` can't be deserialized for webhooks.

In the JSON payload from Space the `ReviewerState.Old` and `ReviewerState.New` can be null but the property `ReviewerState` has the type `Modification<ReviewerState>`.

I think the type should be `Modification<ReviewerState?>`, don't know if `Old` and `New` for `TheirTurn` can be null to.

Kind regards,
Pascal

**Comment by maartenba** [comment]
Do you have an aexception/payload example by any chance? Many thanks in advance!

**Comment by Dabbel** [comment]
Here is the payload and exception.

Payload send from Space:
```json
{
    "className": "WebhookRequestPayload",
    "clientId": "019c8bb3-6848-4e95-b74d-abb2fddbaa99",
    "payload": {
        "className": "CodeReviewParticipantWebhookEvent",
        "isMergeRequest": true,
        "meta": {
            "method": "Updated",
            "principal": {
                "details": {
                    "className": "CUserPrincipalDetails",
                    "user": {
                        "id": "4TUpet38n3Ow"
                    }
                },
                "name": "p.empl"
            },
            "timestamp": {
                "iso": "2024-05-10T19:14:16.438Z",
                "timestamp": 1715368456438
            }
        },
        "participant": {
            "id": "4TUpet38n3Ow"
        },
        "review": {
            "className": "MergeRequestRecord",
            "id": "13E9bi0xGPvU"
        },
        "reviewerState": {
            "new": "Accepted",
            "old": null
        },
        "theirTurn": {
            "new": false,
            "old": null
        }
    },
    "verificationToken": null,
    "webhookId": "4N1tlq2Yszxp"
}
```

Exception:
```
JetBrains.Space.AspNetCore.Experimental.WebHooks.SpaceWebHookRequestHandler: Error: JSON input formatter threw an exception at path $.reviewerState.new: The JSON value could not be converted to JetBrains.Space.Client.ReviewerState.

System.Text.Json.JsonException: The JSON value could not be converted to JetBrains.Space.Client.ReviewerState.
   at JetBrains.Space.Common.Json.Serialization.EnumStringConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at JetBrains.Space.Common.Json.Serialization.Polymorphism.ClassNameDtoTypeConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonConverter jsonConverter, Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.Read[TValue](Utf8JsonReader& reader, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(Utf8JsonReader& reader, Type returnType, JsonSerializerOptions options)
   at JetBrains.Space.Common.Json.Serialization.Polymorphism.ClassNameDtoTypeConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize(String json, Type returnType, JsonSerializerOptions options)
   at JetBrains.Space.AspNetCore.Experimental.WebHooks.SpaceWebHookRequestHandler`1.TryReadPayloadFromRequestAsync(HttpRequest httpRequest)
```

**Comment by maartenba** [comment]
Should be fixed in the latest NuGet packages 👍
