### ISSUE TITLE
System.InvalidCastException: Unable to cast object of type UrlParameterConverter to type 'System.Text.Json.Serialization.JsonConverter`1[JetBrains.Space.Client.SprintIdentifier]'

### ISSUE THREAD

**Issue by brendonofficial** [JetBrains/space-dotnet-sdk#4]
Using the SDK version `1.0.0-beta.83694.9065`, I am calling `CreateIssueAsync` within `JetBrains.Space.Client.ProjectClient.PlanningClient.IssueClient`, as per the following example:
```
var issue = await this._spaceIssueClient.CreateIssueAsync(
    project: ProjectIdentifier.Key("AZ"),
    title: "My issue title here",
    status: openStatus.Id,
    description: "This is an example issue",
    dueDate: DateTime.UtcNow.AddDays(3),
);
```

When calling this method, I am getting the below exception - the result is the same even if I specify a value for the `sprints` parameter:
```
Unable to cast object of type 'JetBrains.Space.Common.Json.Serialization.UrlParameterConverter' to type 'System.Text.Json.Serialization.JsonConverter`1[JetBrains.Space.Client.SprintIdentifier]'
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.GetElementConverter(WriteStack& state)
   at System.Text.Json.Serialization.Converters.ListOfTConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](JsonConverter jsonConverter, Utf8JsonWriter writer, TValue& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.JsonSerializer.WriteCore[TValue](Utf8JsonWriter writer, TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue& value, Type inputType, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at JetBrains.Space.Common.BearerTokenConnection.RequestResourceInternalAsync[TPayload,TResult](String httpMethod, String urlPath, TPayload payload, CancellationToken cancellationToken)
   at JetBrains.Space.Common.Connection.RequestResourceAsync[TPayload,TResult](String httpMethod, String urlPath, TPayload payload, CancellationToken cancellationToken)
   at JetBrains.Space.Client.ProjectClient.PlanningClient.IssueClient.CreateIssueAsync(ProjectIdentifier project, String title, String status, List`1 tags, List`1 checklists, List`1 sprints, String description, ProfileIdentifier assignee, Nullable`1 dueDate, List`1 attachments, MessageLink fromMessage, List`1 customFields, List`1 topics, List`1 parents, Func`2 partial, CancellationToken cancellationToken)
```

**Comment by maartenba** [comment]
Fixed and a new release is up on NuGet. Thanks for the report!

Out of curiosity, what type of app are you building with the SDK?
